import { chmod, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join, sep } from "node:path";
import type { Command } from "commander";
import { action } from "../action.js";

/**
 * `bb install-cli`: put this app's bb on the user's PATH.
 *
 * Not circular. An agent running inside bb already has bb on PATH via
 * runtime-shell-env.ts, so this is exactly the command an agent can run to fix
 * the user's outside-the-app case, without a settings window.
 *
 * This CLI ships inside the daemon bundle and cannot import @bb/desktop, so it
 * re-derives the same paths and marker. The strings below are pinned by tests
 * on both sides.
 */

export const WRAPPER_MARKER =
  "# bb-managed: generated by the bb desktop app. Safe to delete.";
const BUNDLE_CLI_SUFFIX = join(
  "Contents",
  "Resources",
  "app.asar.unpacked",
  "node_modules",
  "bb-app",
  "host-daemon",
  "dist",
  "bb",
);

interface ResolveBundleFromCliPathArgs {
  cliPath: string;
  platform: NodeJS.Platform;
}

interface ResolvedBundle {
  appBundlePath: string;
  commandName: string;
  wrapperPath: string;
}

/**
 * The channel's command name, read from ground truth rather than guessed.
 *
 * apps/desktop/scripts/run-electron-builder.mjs ships the layer-1 wrapper
 * into <bundle>/Contents/Resources/bin/<name> at build time, for exactly one
 * name per bundle. Reading that directory listing is the same ground-truth
 * approach as apps/desktop/src/cli-link.ts's resolveCliCommandName, whose
 * docstring explains why: a name-based guess (e.g. matching the bundle's
 * directory name against "bb Nightly.app") would let a renamed or drifted
 * bundle silently write ~/.bb/bin/bb for what is actually a different
 * channel, shadowing a real install. Anything other than exactly one entry is
 * treated the same as "no bundle found" rather than guessed at.
 */
async function resolveBundleCommandName(
  appBundlePath: string,
): Promise<string | null> {
  const binDir = join(appBundlePath, "Contents", "Resources", "bin");
  let entries: string[];
  try {
    entries = await readdir(binDir);
  } catch {
    return null;
  }
  if (entries.length !== 1) {
    return null;
  }
  const [commandName] = entries;
  return commandName ?? null;
}

/**
 * Locate the containing .app from the running CLI's own path.
 *
 * macOS only: a Linux AppImage mounts at a different ephemeral path each
 * launch, so ~/.bb/bin has to be written by the app from $APPIMAGE at launch
 * rather than by the CLI from where it happens to be running.
 */
export async function resolveBundleFromCliPath(
  args: ResolveBundleFromCliPathArgs,
): Promise<ResolvedBundle | null> {
  if (args.platform !== "darwin") {
    return null;
  }
  if (!args.cliPath.endsWith(`${sep}${BUNDLE_CLI_SUFFIX}`)) {
    return null;
  }

  const appBundlePath = args.cliPath.slice(
    0,
    args.cliPath.length - BUNDLE_CLI_SUFFIX.length - 1,
  );
  if (!appBundlePath.endsWith(".app")) {
    return null;
  }

  const commandName = await resolveBundleCommandName(appBundlePath);
  if (commandName === null) {
    return null;
  }

  return {
    appBundlePath,
    commandName,
    wrapperPath: join(
      appBundlePath,
      "Contents",
      "Resources",
      "bin",
      commandName,
    ),
  };
}

/**
 * Single-quote a value for POSIX sh. Mirrors
 * apps/desktop/src/cli-wrapper-script.ts's `shellQuote`: a double-quoted
 * interpolation does not suppress `$`/backtick expansion, so any path
 * embedded in the generated script must go through a variable assignment
 * quoted this way rather than being interpolated directly into a string.
 */
function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function createHomeWrapper(bundle: ResolvedBundle): string {
  return `#!/bin/sh
${WRAPPER_MARKER}
# ${bundle.commandName}: rewritten by the bb desktop app on every launch.
set -e

WRAPPER=${shellQuote(bundle.wrapperPath)}
APP_BUNDLE=${shellQuote(bundle.appBundlePath)}

if [ ! -x "$WRAPPER" ]; then
  echo "${bundle.commandName}: the bb app is no longer installed at $APP_BUNDLE" >&2
  echo "${bundle.commandName}: reinstall it, or remove this file" >&2
  exit 127
fi

exec "$WRAPPER" "$@"
`;
}

async function isOursOrAbsent(path: string): Promise<boolean> {
  try {
    return (await readFile(path, "utf8")).includes(WRAPPER_MARKER);
  } catch (error) {
    return (error as NodeJS.ErrnoException).code === "ENOENT";
  }
}

interface RunInstallCliArgs {
  cliPath: string;
  homeDir: string;
  platform: NodeJS.Platform;
}

interface RunInstallCliResult {
  binDir: string;
  commandName: string;
  wrapperPath: string;
}

/**
 * The install logic behind `bb install-cli`, factored out from the Commander
 * action so it can take an injectable `homeDir` and `cliPath` for testing
 * without touching the real $HOME or requiring a real packaged bundle.
 */
export async function runInstallCli(
  args: RunInstallCliArgs,
): Promise<RunInstallCliResult> {
  const bundle = await resolveBundleFromCliPath({
    cliPath: args.cliPath,
    platform: args.platform,
  });

  if (bundle === null) {
    if (args.platform === "linux") {
      throw new Error(
        "On Linux the bb command is written by the desktop app at launch. Start the bb AppImage once, then add ~/.bb/bin to PATH.",
      );
    }
    throw new Error(
      "This bb is not running from a packaged bb.app, so there is no app bundle to link. Install the desktop app, or use the npm-global bb you already have on PATH.",
    );
  }

  const binDir = join(args.homeDir, ".bb", "bin");
  const wrapperPath = join(binDir, bundle.commandName);

  if (!(await isOursOrAbsent(wrapperPath))) {
    throw new Error(
      `${wrapperPath} was not written by bb, so it was left alone. Remove it and re-run to let bb manage this command.`,
    );
  }

  await mkdir(binDir, { recursive: true });
  await writeFile(wrapperPath, createHomeWrapper(bundle));
  await chmod(wrapperPath, 0o755);

  return { binDir, commandName: bundle.commandName, wrapperPath };
}

export function registerInstallCliCommand(program: Command): void {
  program
    .command("install-cli")
    .description("Install this app's bb command into ~/.bb/bin")
    .action(
      action(async () => {
        const { binDir, commandName, wrapperPath } = await runInstallCli({
          cliPath: process.argv[1] ?? "",
          homeDir: homedir(),
          platform: process.platform,
        });

        console.log(`Installed ${commandName} at ${wrapperPath}`);
        if (!(process.env.PATH ?? "").split(":").includes(binDir)) {
          console.log(
            `Add it to your PATH:\n\n  export PATH="$HOME/.bb/bin:$PATH"\n`,
          );
        }
      }),
    );
}
