import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join, sep } from "node:path";
import type { Command } from "commander";
import { action } from "../action.js";

/**
 * `bb install-cli`: put this app's bb on the user's PATH.
 *
 * Not circular. An agent running inside bb already has bb on PATH via
 * runtime-shell-env.ts, so this is exactly the command an agent can run to fix
 * the user's outside-the-app case, without a settings window.
 *
 * This CLI ships inside the daemon bundle and cannot import @bb/desktop, so it
 * re-derives the same paths and marker. The strings below are pinned by tests
 * on both sides.
 */

const WRAPPER_MARKER =
  "# bb-managed: generated by the bb desktop app. Safe to delete.";
const BUNDLE_CLI_SUFFIX = join(
  "Contents",
  "Resources",
  "app.asar.unpacked",
  "node_modules",
  "bb-app",
  "host-daemon",
  "dist",
  "bb",
);

interface ResolveBundleFromCliPathArgs {
  cliPath: string;
  platform: NodeJS.Platform;
}

interface ResolvedBundle {
  appBundlePath: string;
  commandName: string;
  wrapperPath: string;
}

/**
 * Locate the containing .app from the running CLI's own path.
 *
 * macOS only: a Linux AppImage mounts at a different ephemeral path each
 * launch, so ~/.bb/bin has to be written by the app from $APPIMAGE at launch
 * rather than by the CLI from where it happens to be running.
 */
export function resolveBundleFromCliPath(
  args: ResolveBundleFromCliPathArgs,
): ResolvedBundle | null {
  if (args.platform !== "darwin") {
    return null;
  }
  if (!args.cliPath.endsWith(`${sep}${BUNDLE_CLI_SUFFIX}`)) {
    return null;
  }

  const appBundlePath = args.cliPath.slice(
    0,
    args.cliPath.length - BUNDLE_CLI_SUFFIX.length - 1,
  );
  if (!appBundlePath.endsWith(".app")) {
    return null;
  }

  const commandName = appBundlePath.endsWith("bb Nightly.app")
    ? "bb-nightly"
    : "bb";

  return {
    appBundlePath,
    commandName,
    wrapperPath: join(
      appBundlePath,
      "Contents",
      "Resources",
      "bin",
      commandName,
    ),
  };
}

function createHomeWrapper(bundle: ResolvedBundle): string {
  return `#!/bin/sh
${WRAPPER_MARKER}
# ${bundle.commandName}: rewritten by the bb desktop app on every launch.
set -e

WRAPPER='${bundle.wrapperPath.replaceAll("'", `'\\''`)}'

if [ ! -x "$WRAPPER" ]; then
  echo "${bundle.commandName}: the bb app is no longer installed at ${bundle.appBundlePath}" >&2
  echo "${bundle.commandName}: reinstall it, or remove this file" >&2
  exit 127
fi

exec "$WRAPPER" "$@"
`;
}

async function isOursOrAbsent(path: string): Promise<boolean> {
  try {
    return (await readFile(path, "utf8")).includes(WRAPPER_MARKER);
  } catch (error) {
    return (error as NodeJS.ErrnoException).code === "ENOENT";
  }
}

export function registerInstallCliCommand(program: Command): void {
  program
    .command("install-cli")
    .description("Install this app's bb command into ~/.bb/bin")
    .action(
      action(async () => {
        const bundle = resolveBundleFromCliPath({
          cliPath: process.argv[1] ?? "",
          platform: process.platform,
        });

        if (bundle === null) {
          if (process.platform === "linux") {
            throw new Error(
              "On Linux the bb command is written by the desktop app at launch. Start the bb AppImage once, then add ~/.bb/bin to PATH.",
            );
          }
          throw new Error(
            "This bb is not running from a packaged bb.app, so there is no app bundle to link. Install the desktop app, or use the npm-global bb you already have on PATH.",
          );
        }

        const binDir = join(homedir(), ".bb", "bin");
        const wrapperPath = join(binDir, bundle.commandName);

        if (!(await isOursOrAbsent(wrapperPath))) {
          throw new Error(
            `${wrapperPath} was not written by bb, so it was left alone. Remove it and re-run to let bb manage this command.`,
          );
        }

        await mkdir(binDir, { recursive: true });
        await writeFile(wrapperPath, createHomeWrapper(bundle));
        await chmod(wrapperPath, 0o755);

        console.log(`Installed ${bundle.commandName} at ${wrapperPath}`);
        if (!(process.env.PATH ?? "").split(":").includes(binDir)) {
          console.log(
            `Add it to your PATH:\n\n  export PATH="$HOME/.bb/bin:$PATH"\n`,
          );
        }
      }),
    );
}
