/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConnectRedeemMachineRouteImport } from './routes/api.connect.redeem-machine'
import { Route as ApiConnectRedeemRouteImport } from './routes/api.connect.redeem'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectRedeemMachineRoute = ApiConnectRedeemMachineRouteImport.update({
  id: '/api/connect/redeem-machine',
  path: '/api/connect/redeem-machine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectRedeemRoute = ApiConnectRedeemRouteImport.update({
  id: '/api/connect/redeem',
  path: '/api/connect/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connect/redeem': typeof ApiConnectRedeemRoute
  '/api/connect/redeem-machine': typeof ApiConnectRedeemMachineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connect/redeem': typeof ApiConnectRedeemRoute
  '/api/connect/redeem-machine': typeof ApiConnectRedeemMachineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connect/redeem': typeof ApiConnectRedeemRoute
  '/api/connect/redeem-machine': typeof ApiConnectRedeemMachineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/api/connect/redeem'
    | '/api/connect/redeem-machine'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/api/connect/redeem'
    | '/api/connect/redeem-machine'
  id:
    | '__root__'
    | '/'
    | '/api/auth/$'
    | '/api/connect/redeem'
    | '/api/connect/redeem-machine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConnectRedeemRoute: typeof ApiConnectRedeemRoute
  ApiConnectRedeemMachineRoute: typeof ApiConnectRedeemMachineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connect/redeem-machine': {
      id: '/api/connect/redeem-machine'
      path: '/api/connect/redeem-machine'
      fullPath: '/api/connect/redeem-machine'
      preLoaderRoute: typeof ApiConnectRedeemMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connect/redeem': {
      id: '/api/connect/redeem'
      path: '/api/connect/redeem'
      fullPath: '/api/connect/redeem'
      preLoaderRoute: typeof ApiConnectRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConnectRedeemRoute: ApiConnectRedeemRoute,
  ApiConnectRedeemMachineRoute: ApiConnectRedeemMachineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
