// GENERATED FILE — do not edit by hand.
// Named exports of the shared React runtime modules (react@19.2.4),
// introspected from the host app's installed React. Consumed by
// `bb plugin build` to emit static ESM re-export shims over
// globalThis.__bbPluginRuntime. Regenerate after a React upgrade:
//   node packages/plugin-build/scripts/generate-runtime-export-manifest.mjs

export const RUNTIME_EXPORT_MANIFEST: Record<string, readonly string[]> = {
  "react": [
    "Activity",
    "Children",
    "Component",
    "Fragment",
    "Profiler",
    "PureComponent",
    "StrictMode",
    "Suspense",
    "act",
    "cache",
    "cacheSignal",
    "captureOwnerStack",
    "cloneElement",
    "createContext",
    "createElement",
    "createRef",
    "forwardRef",
    "isValidElement",
    "lazy",
    "memo",
    "startTransition",
    "unstable_useCacheRefresh",
    "use",
    "useActionState",
    "useCallback",
    "useContext",
    "useDebugValue",
    "useDeferredValue",
    "useEffect",
    "useEffectEvent",
    "useId",
    "useImperativeHandle",
    "useInsertionEffect",
    "useLayoutEffect",
    "useMemo",
    "useOptimistic",
    "useReducer",
    "useRef",
    "useState",
    "useSyncExternalStore",
    "useTransition",
    "version",
  ],
  "react-dom": [
    "createPortal",
    "flushSync",
    "preconnect",
    "prefetchDNS",
    "preinit",
    "preinitModule",
    "preload",
    "preloadModule",
    "requestFormReset",
    "unstable_batchedUpdates",
    "useFormState",
    "useFormStatus",
    "version",
  ],
  "react-dom/client": [
    "createRoot",
    "hydrateRoot",
    "version",
  ],
  "react/jsx-runtime": [
    "Fragment",
    "jsx",
    "jsxs",
  ],
  "react/jsx-dev-runtime": [
    "Fragment",
    "jsxDEV",
  ],
};
