import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react";
import {
  Airplane01Icon,
  Alien01Icon,
  AnchorIcon,
  Atom01Icon,
  BalloonsIcon,
  BananaIcon,
  Bicycle01Icon,
  BirdIcon,
  BirthdayCakeIcon,
  BoatIcon,
  Book01Icon,
  BookOpen01Icon,
  BrainIcon,
  Briefcase01Icon,
  Bug01Icon,
  Building01Icon,
  Bus01Icon,
  CactusIcon,
  Camera01Icon,
  Car01Icon,
  Castle01Icon,
  ChessPawnIcon,
  ChipIcon,
  City01Icon,
  CloudIcon,
  CloudServerIcon,
  Coffee01Icon,
  CommandLineIcon,
  Compass01Icon,
  ComputerIcon,
  ConsoleIcon,
  CpuIcon,
  CrownIcon,
  DatabaseIcon,
  Diamond01Icon,
  DiceIcon,
  DnaIcon,
  DropletIcon,
  EarthIcon,
  EyeIcon,
  Factory01Icon,
  FavouriteIcon,
  Film01Icon,
  FingerPrintIcon,
  FireIcon,
  FireworksIcon,
  FishSymbolIcon,
  Flag01Icon,
  FlashIcon,
  FlowerIcon,
  FlowerPotIcon,
  GameController01Icon,
  GalaxyIcon,
  GiftIcon,
  GitBranchIcon,
  Globe02Icon,
  Hamburger01Icon,
  HardDriveIcon,
  HeadphonesIcon,
  Home01Icon,
  Idea01Icon,
  IceCream01Icon,
  Infinity01Icon,
  Key01Icon,
  LaptopIcon,
  Leaf01Icon,
  MagicWand01Icon,
  MapsIcon,
  Medal01Icon,
  Mic01Icon,
  MicroscopeIcon,
  Moon02Icon,
  Mortarboard01Icon,
  Motorbike01Icon,
  MountainIcon,
  Mushroom01Icon,
  MusicNote01Icon,
  OctopusIcon,
  PaintBrush01Icon,
  PartyIcon,
  PenTool03Icon,
  Pizza01Icon,
  PuzzleIcon,
  RainbowIcon,
  Robot01Icon,
  Rocket01Icon,
  SailboatCoastalIcon,
  SaturnIcon,
  ServerStack01Icon,
  Shield01Icon,
  SkullIcon,
  SmartPhone01Icon,
  SnowIcon,
  SourceCodeIcon,
  SparklesIcon,
  SquareLock01Icon,
  StarIcon,
  Sun03Icon,
  Sword01Icon,
  Target02Icon,
  Telescope01Icon,
  TentIcon,
  TerminalIcon,
  TestTube01Icon,
  Train01Icon,
  Tree01Icon,
  TruckIcon,
  UmbrellaIcon,
  Video01Icon,
} from "@hugeicons/core-free-icons";

/**
 * Server-tile identity icons: a hand-picked set for telling machines apart
 * (devices, places, nature, creatures, objects) — deliberately separate from
 * the app's UI icon vocabulary in @bb/shared-ui, which is full of arrows and
 * chrome glyphs that make no sense as a server logo. Keys are the persisted
 * icon ids; keep them stable ("Zap" predates this registry). Named imports
 * keep the bundle tree-shaken to just this set.
 */
export const SERVER_TILE_ICON_MAP: Record<string, IconSvgElement> = {
  Airplane: Airplane01Icon,
  Alien: Alien01Icon,
  Anchor: AnchorIcon,
  Atom: Atom01Icon,
  Balloons: BalloonsIcon,
  Banana: BananaIcon,
  Bicycle: Bicycle01Icon,
  Bird: BirdIcon,
  Boat: BoatIcon,
  Book: Book01Icon,
  BookOpen: BookOpen01Icon,
  Brain: BrainIcon,
  Briefcase: Briefcase01Icon,
  Bug: Bug01Icon,
  Building: Building01Icon,
  Bus: Bus01Icon,
  Cactus: CactusIcon,
  Cake: BirthdayCakeIcon,
  Camera: Camera01Icon,
  Car: Car01Icon,
  Castle: Castle01Icon,
  ChessPawn: ChessPawnIcon,
  Chip: ChipIcon,
  City: City01Icon,
  Cloud: CloudIcon,
  CloudServer: CloudServerIcon,
  Coffee: Coffee01Icon,
  CommandLine: CommandLineIcon,
  Compass: Compass01Icon,
  Computer: ComputerIcon,
  Console: ConsoleIcon,
  Cpu: CpuIcon,
  Crown: CrownIcon,
  Database: DatabaseIcon,
  Diamond: Diamond01Icon,
  Dice: DiceIcon,
  Dna: DnaIcon,
  Droplet: DropletIcon,
  Earth: EarthIcon,
  Eye: EyeIcon,
  Factory: Factory01Icon,
  Film: Film01Icon,
  Fingerprint: FingerPrintIcon,
  Fire: FireIcon,
  Fireworks: FireworksIcon,
  Fish: FishSymbolIcon,
  Flag: Flag01Icon,
  Flower: FlowerIcon,
  FlowerPot: FlowerPotIcon,
  Galaxy: GalaxyIcon,
  Gamepad: GameController01Icon,
  Gift: GiftIcon,
  GitBranch: GitBranchIcon,
  Globe: Globe02Icon,
  GraduationCap: Mortarboard01Icon,
  Hamburger: Hamburger01Icon,
  HardDrive: HardDriveIcon,
  Headphones: HeadphonesIcon,
  Heart: FavouriteIcon,
  Home: Home01Icon,
  IceCream: IceCream01Icon,
  Idea: Idea01Icon,
  Infinity: Infinity01Icon,
  Key: Key01Icon,
  Laptop: LaptopIcon,
  Leaf: Leaf01Icon,
  Lock: SquareLock01Icon,
  MagicWand: MagicWand01Icon,
  Map: MapsIcon,
  Medal: Medal01Icon,
  Mic: Mic01Icon,
  Microscope: MicroscopeIcon,
  Moon: Moon02Icon,
  Motorbike: Motorbike01Icon,
  Mountain: MountainIcon,
  Mushroom: Mushroom01Icon,
  MusicNote: MusicNote01Icon,
  Octopus: OctopusIcon,
  PaintBrush: PaintBrush01Icon,
  Party: PartyIcon,
  PenTool: PenTool03Icon,
  Pizza: Pizza01Icon,
  Puzzle: PuzzleIcon,
  Rainbow: RainbowIcon,
  Robot: Robot01Icon,
  Rocket: Rocket01Icon,
  Sailboat: SailboatCoastalIcon,
  Saturn: SaturnIcon,
  Server: ServerStack01Icon,
  Shield: Shield01Icon,
  Skull: SkullIcon,
  Smartphone: SmartPhone01Icon,
  Snow: SnowIcon,
  SourceCode: SourceCodeIcon,
  Sparkles: SparklesIcon,
  Star: StarIcon,
  Sun: Sun03Icon,
  Sword: Sword01Icon,
  Target: Target02Icon,
  Telescope: Telescope01Icon,
  Tent: TentIcon,
  Terminal: TerminalIcon,
  TestTube: TestTube01Icon,
  Train: Train01Icon,
  Tree: Tree01Icon,
  Truck: TruckIcon,
  Umbrella: UmbrellaIcon,
  Video: Video01Icon,
  Zap: FlashIcon,
};

export type ServerTileIconName = keyof typeof SERVER_TILE_ICON_MAP;

export const SERVER_TILE_ICON_NAMES = Object.keys(
  SERVER_TILE_ICON_MAP,
) as readonly ServerTileIconName[];

export interface ServerTileIconProps {
  name: ServerTileIconName;
  className?: string;
  "aria-hidden"?: boolean | "true" | "false";
}

export function ServerTileIcon({
  name,
  className,
  "aria-hidden": ariaHidden,
}: ServerTileIconProps) {
  return (
    <HugeiconsIcon
      icon={SERVER_TILE_ICON_MAP[name]}
      className={className}
      aria-hidden={ariaHidden}
      data-icon={name}
    />
  );
}
