/**
 * Shell text for the two wrappers this feature writes.
 *
 * Kept as pure string generation with no filesystem or Electron dependency so
 * both the launch-time refresh and the `bb install-cli` command can produce
 * byte-identical output, and so the shapes can be asserted in a plain unit
 * test rather than only in a packaged smoke run.
 */

/**
 * Line 2 of every file this feature writes. A target path holding a file
 * without this line belongs to someone else and is never overwritten.
 */
export const BB_CLI_WRAPPER_MARKER =
  "# bb-managed: generated by the bb desktop app. Safe to delete.";

/** Path to the bundled CLI, relative to a bundle's resources directory. */
export const BB_CLI_BUNDLE_RELATIVE_CLI_PATH =
  "app.asar.unpacked/node_modules/bb-app/host-daemon/dist/bb";

export type BbCliWrapperTarget =
  | {
      kind: "macos-bundle";
      /** Bundle root, e.g. /Applications/bb.app. Named in the diagnostic. */
      appBundlePath: string;
      /** The layer-1 wrapper inside that bundle. */
      wrapperPath: string;
    }
  | {
      kind: "linux-appimage";
      /** Recorded from process.env.APPIMAGE at launch. */
      appImagePath: string;
      bootstrapPath: string;
    };

interface CreateBundleCliWrapperScriptArgs {
  commandName: string;
  /** electron-builder's productName, e.g. "bb" or "bb Nightly". */
  macExecutableName: string;
}

interface CreateHomeCliWrapperScriptArgs {
  commandName: string;
  target: BbCliWrapperTarget;
}

/**
 * Layer 1: ships inside the macOS bundle at Contents/Resources/bin/<name>.
 *
 * Self-locates via $0, so it needs no recorded path and no refresh: it moves
 * with the app. This is the single place that knows the bundle-internal
 * layout, which is what lets a months-old layer-2 wrapper keep working after
 * the layout changes.
 *
 * The symlink walk is hand-rolled because macOS ships the BSD realpath(1),
 * which has not always been present. VS Code hand-rolls it in code.sh for the
 * same reason, and so does this repo's bin/bb.
 */
export function createBundleCliWrapperScript(
  args: CreateBundleCliWrapperScriptArgs,
): string {
  return `#!/bin/sh
${BB_CLI_WRAPPER_MARKER}
# ${args.commandName}: run this bundle's bb CLI.
set -e

SELF="$0"
while [ -L "$SELF" ]; do
  LINK=$(readlink "$SELF")
  case "$LINK" in
    /*) SELF="$LINK" ;;
    *) SELF="$(dirname -- "$SELF")/$LINK" ;;
  esac
done

# <bundle>/Contents/Resources/bin/<name> -> <bundle>
BIN_DIR=$(CDPATH= cd -- "$(dirname -- "$SELF")" && pwd)
RESOURCES_DIR=$(CDPATH= cd -- "$BIN_DIR/.." && pwd)
APP=$(CDPATH= cd -- "$RESOURCES_DIR/../.." && pwd)

# Electron prints a node_main.cc warning to stderr on every invocation when
# NODE_OPTIONS is set. Stash rather than discard so the CLI can re-apply it to
# node children it spawns.
if [ -n "\${NODE_OPTIONS:-}" ]; then
  BB_NODE_OPTIONS="$NODE_OPTIONS"
  export BB_NODE_OPTIONS
  unset NODE_OPTIONS
fi

exec env ELECTRON_RUN_AS_NODE=1 \\
  "$APP/Contents/MacOS/${args.macExecutableName}" \\
  "$RESOURCES_DIR/${BB_CLI_BUNDLE_RELATIVE_CLI_PATH}" "$@"
`;
}

/**
 * Layer 2: written to ~/.bb/bin/<name> on every launch.
 *
 * A generated wrapper rather than a symlink on both platforms. A dangling
 * symlink reports "command not found" in zsh and bash (verified), which is
 * misleading because the file is present. The wrapper names the real cause and
 * exits 127. Using a wrapper on both platforms also collapses generation,
 * refresh, and the diagnostic into one code path.
 */
export function createHomeCliWrapperScript(
  args: CreateHomeCliWrapperScriptArgs,
): string {
  const header = `#!/bin/sh
${BB_CLI_WRAPPER_MARKER}
# ${args.commandName}: rewritten by the bb desktop app on every launch.
set -e
`;

  if (args.target.kind === "macos-bundle") {
    return `${header}
WRAPPER="${args.target.wrapperPath}"

if [ ! -x "$WRAPPER" ]; then
  echo "${args.commandName}: the bb app is no longer installed at ${args.target.appBundlePath}" >&2
  echo "${args.commandName}: reinstall it, or remove this file" >&2
  exit 127
fi

exec "$WRAPPER" "$@"
`;
  }

  return `${header}
APPIMG="${args.target.appImagePath}"
BOOTSTRAP="${args.target.bootstrapPath}"

if [ ! -x "$APPIMG" ]; then
  echo "${args.commandName}: the bb AppImage is no longer at ${args.target.appImagePath}" >&2
  echo "${args.commandName}: move it back and relaunch bb, or remove this file" >&2
  exit 127
fi
if [ ! -f "$BOOTSTRAP" ]; then
  echo "${args.commandName}: missing bootstrap at ${args.target.bootstrapPath}" >&2
  echo "${args.commandName}: relaunch bb to rewrite it" >&2
  exit 127
fi

if [ -n "\${NODE_OPTIONS:-}" ]; then
  BB_NODE_OPTIONS="$NODE_OPTIONS"
  export BB_NODE_OPTIONS
  unset NODE_OPTIONS
fi

exec env ELECTRON_RUN_AS_NODE=1 "$APPIMG" "$BOOTSTRAP" "$@"
`;
}

/**
 * Linux only. An AppImage self-mounts at a different ephemeral path each
 * launch, so no path inside it is stable enough to record. The wrapper records
 * the stable $APPIMAGE file; this bootstrap runs *inside* the mount and reads
 * $APPDIR to find the CLI. Both variables were verified reaching the Node
 * process through AppRun.
 */
export function createAppImageBootstrapScript(): string {
  return `${BB_CLI_WRAPPER_MARKER.replace("#", "//")}
import { join } from "node:path";

const appDir = process.env.APPDIR;
if (appDir === undefined || appDir.length === 0) {
  console.error("bb: APPDIR is unset, so the bundled CLI cannot be located.");
  process.exit(127);
}

await import(
  join(appDir, "resources/${BB_CLI_BUNDLE_RELATIVE_CLI_PATH}")
);
`;
}
