import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import {
  APP_RUNTIME_BROWSER_BUNDLE,
  APP_RUNTIME_BROWSER_BUNDLE_SHA256,
} from "../src/app-runtime-browser-bundle.generated.js";

// The bundle is regenerated by the @bb/sdk#generate:app-runtime-browser-bundle
// turbo task before this suite runs, so these assertions always exercise a
// fresh build of the runtime source graph.
describe("app runtime browser bundle codegen", () => {
  it("publishes the sha256 the server uses as the immutable asset cache key", () => {
    expect(APP_RUNTIME_BROWSER_BUNDLE_SHA256).toBe(
      createHash("sha256")
        .update(APP_RUNTIME_BROWSER_BUNDLE, "utf8")
        .digest("hex"),
    );
  });

  it("embeds guide templates only", () => {
    expect(APP_RUNTIME_BROWSER_BUNDLE).toContain("bbGuideApp");
    expect(APP_RUNTIME_BROWSER_BUNDLE).not.toContain("agentThreadMessage");
  });
});
