CREATE TABLE `machine_lifecycles` (
	`host_id` text PRIMARY KEY NOT NULL,
	`observed_state` text NOT NULL,
	`observed_at` integer NOT NULL,
	`expires_at` integer,
	`maintenance_at` integer,
	`last_snapshot_at` integer,
	`recovery_state` text NOT NULL,
	`message` text,
	`lease_id` text,
	`lease_until` integer,
	`retry_at` integer,
	`idle_suspend_ms` integer,
	`retire_after_ms` integer,
	`deadline_lead_ms` integer,
	`unused_since` integer,
	`retention_at` integer,
	`keep` integer DEFAULT false NOT NULL,
	FOREIGN KEY (`host_id`) REFERENCES `hosts`(`id`) ON UPDATE no action ON DELETE cascade
);
