import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react";
import {
  Alert02Icon,
  AlertCircleIcon,
  Archive03Icon,
  ArrowDown01Icon,
  ArrowDown02Icon,
  ArrowDownDoubleIcon,
  ArrowExpand01Icon,
  ArrowLeft01Icon,
  ArrowMoveDownLeftIcon,
  ArrowMoveDownRightIcon,
  ArrowRight01Icon,
  ArrowRight02Icon,
  ArrowShrink01Icon,
  ArrowUp01Icon,
  ArrowUp02Icon,
  ArrowUpDoubleIcon,
  ArrowTurnBackwardIcon,
  ArrowTurnForwardIcon,
  ArrowUpRight01Icon,
  AttachmentIcon,
  AudioWaveIcon,
  BrowserIcon,
  BubbleChatAddIcon,
  BubbleChatIcon,
  Cancel01Icon,
  CancelCircleIcon,
  ChartColumnIcon,
  CheckListIcon,
  CheckmarkCircle02Icon,
  CircleIcon,
  Clock01Icon,
  CloudIcon,
  Book02Icon,
  ComputerTerminal01Icon,
  Copy01Icon,
  DashedLine02Icon,
  DashedLineCircleIcon,
  Delete02Icon,
  DragDropVerticalIcon,
  Edit02Icon,
  Edit04Icon,
  File01Icon,
  FileEmpty02Icon,
  FileQuestionMarkIcon,
  FileXIcon,
  Folder02Icon,
  FolderAddIcon,
  FolderGitTwoIcon,
  FolderIcon,
  FolderRemoveIcon,
  GitBranchIcon,
  GitMergeIcon,
  GridViewIcon,
  InformationCircleIcon,
  InternetIcon,
  LaptopIcon,
  LockIcon,
  LayoutTwoColumnIcon,
  LayoutTwoRowIcon,
  LinkSquare02Icon,
  Menu02Icon,
  MessageAdd02Icon,
  MessageQuestionIcon,
  Mic02Icon,
  MoreHorizontalIcon,
  PlusMinusSquare01Icon,
  PlusSignIcon,
  Refresh01Icon,
  Search01Icon,
  SentIcon,
  Settings01Icon,
  SidebarBottomIcon,
  SidebarLeftIcon,
  SidebarRightIcon,
  SourceCodeIcon,
  SquareIcon,
  Target02Icon,
  TextWrapIcon,
  Tick02Icon,
  TrendingUpDownIcon,
  Unarchive03Icon,
  UserAdd01Icon,
  UserIcon,
  ZapIcon,
  ZoomInAreaIcon,
  ZoomOutAreaIcon,
} from "@hugeicons/core-free-icons";
import { cn } from "@/lib/utils";

const ICON_MAP = {
  AlertCircle: AlertCircleIcon,
  AlertTriangle: Alert02Icon,
  AlignLeft: Menu02Icon,
  AppWindow: BrowserIcon,
  Archive: Archive03Icon,
  ArchiveRestore: Unarchive03Icon,
  ArrowDown: ArrowDown02Icon,
  ArrowRight: ArrowRight02Icon,
  ArrowUp: ArrowUp02Icon,
  ArrowTurnBackward: ArrowTurnBackwardIcon,
  ArrowTurnForward: ArrowTurnForwardIcon,
  ArrowUpRight: ArrowUpRight01Icon,
  AudioLines: AudioWaveIcon,
  Browser: BrowserIcon,
  ChartColumn: ChartColumnIcon,
  Check: Tick02Icon,
  ChevronDown: ArrowDown01Icon,
  ChevronLeft: ArrowLeft01Icon,
  ChevronRight: ArrowRight01Icon,
  ChevronUp: ArrowUp01Icon,
  ChevronsDown: ArrowDownDoubleIcon,
  ChevronsUp: ArrowUpDoubleIcon,
  Circle: CircleIcon,
  CircleCheck: CheckmarkCircle02Icon,
  CircleDashed: DashedLineCircleIcon,
  CircleX: CancelCircleIcon,
  Clock: Clock01Icon,
  Code: SourceCodeIcon,
  Columns2: LayoutTwoColumnIcon,
  Container: CloudIcon,
  Copy: Copy01Icon,
  CornerDownLeft: ArrowMoveDownLeftIcon,
  CornerDownRight: ArrowMoveDownRightIcon,
  DragDropVertical: DragDropVerticalIcon,
  Edit: Edit02Icon,
  EditFile: Edit04Icon,
  Explore: Book02Icon,
  ExternalLink: LinkSquare02Icon,
  FileDiff: PlusMinusSquare01Icon,
  File: FileEmpty02Icon,
  FileQuestion: FileQuestionMarkIcon,
  FileText: File01Icon,
  FileX2: FileXIcon,
  Folder: FolderIcon,
  FolderGit: FolderGitTwoIcon,
  FolderOpen: Folder02Icon,
  FolderMinus: FolderRemoveIcon,
  FolderPlus: FolderAddIcon,
  Fork: TrendingUpDownIcon,
  GitBranch: GitBranchIcon,
  GitMerge: GitMergeIcon,
  Globe: InternetIcon,
  GridView: GridViewIcon,
  Info: InformationCircleIcon,
  Laptop: LaptopIcon,
  ListTodo: CheckListIcon,
  Lock: LockIcon,
  Maximize2: ArrowExpand01Icon,
  MessageQuestion: MessageQuestionIcon,
  MessageSquarePlus: BubbleChatAddIcon,
  MessageSquare: BubbleChatIcon,
  Mic: Mic02Icon,
  Minimize2: ArrowShrink01Icon,
  MoreHorizontal: MoreHorizontalIcon,
  NewTab: DashedLine02Icon,
  PanelBottom: SidebarBottomIcon,
  PanelLeft: SidebarLeftIcon,
  PanelRight: SidebarRightIcon,
  Paperclip: AttachmentIcon,
  Plus: PlusSignIcon,
  RotateCcw: Refresh01Icon,
  Rows2: LayoutTwoRowIcon,
  Search: Search01Icon,
  Sent: SentIcon,
  Settings: Settings01Icon,
  SideChat: MessageAdd02Icon,
  Spinner: DashedLineCircleIcon,
  Square: SquareIcon,
  Target: Target02Icon,
  Terminal: ComputerTerminal01Icon,
  TextWrap: TextWrapIcon,
  Trash2: Delete02Icon,
  UserRound: UserIcon,
  UserRoundPlus: UserAdd01Icon,
  X: Cancel01Icon,
  Zap: ZapIcon,
  ZoomIn: ZoomInAreaIcon,
  ZoomOut: ZoomOutAreaIcon,
} as const satisfies Record<string, IconSvgElement>;

export type IconName = keyof typeof ICON_MAP;

export const ICON_NAMES = Object.keys(ICON_MAP) as readonly IconName[];

export interface IconProps {
  name: IconName;
  className?: string;
  "aria-hidden"?: boolean | "true" | "false";
  "aria-label"?: string;
}

export function Icon({
  name,
  className,
  "aria-hidden": ariaHidden,
  "aria-label": ariaLabel,
}: IconProps) {
  return (
    <HugeiconsIcon
      icon={ICON_MAP[name]}
      className={cn(className)}
      aria-hidden={ariaHidden}
      aria-label={ariaLabel}
      data-icon={name}
    />
  );
}
