export * from "./api-client.js";
export * from "./api-types.js";
export * from "./api/thread-tabs.js";
export * from "./common.js";
export * from "./errors.js";
export * from "./public-api.js";
export * from "./thread-timeline.js";

export { typedRoutes } from "@bb/hono-typed-routes";

export {
  TERMINAL_COLS_MAX,
  TERMINAL_DATA_MAX_BASE64_LENGTH,
  TERMINAL_DATA_MAX_BYTES,
  TERMINAL_ROWS_MAX,
} from "@bb/domain";

export {
  BROWSER_AUTOMATION_DEFAULT_TIMEOUT_MS,
  BROWSER_AUTOMATION_MAX_AX_DEPTH,
  BROWSER_AUTOMATION_MAX_AX_NODES,
  BROWSER_AUTOMATION_MAX_SCREENSHOT_BYTES,
  BROWSER_AUTOMATION_MAX_TARGETS_PER_THREAD,
  BROWSER_AUTOMATION_MAX_TEXT_LENGTH,
  BROWSER_AUTOMATION_MAX_TIMEOUT_MS,
  BROWSER_AUTOMATION_MAX_URL_LENGTH,
  browserAutomationCapabilityMessageSchema,
  browserAutomationCapabilityUnavailableMessageSchema,
  browserAutomationCancelMessageLenientSchema,
  browserAutomationCancelMessageSchema,
  browserAutomationCancelRequestMessageSchema,
  browserAutomationClientUnavailableReasonSchema,
  browserAutomationCommandErrorCodeSchema,
  browserAutomationCommandFailedMessageSchema,
  browserAutomationCommandMessageLenientSchema,
  browserAutomationCommandMessageSchema,
  browserAutomationCommandResultMessageSchema,
  browserAutomationCommandResultSchema,
  browserAutomationCommandSchema,
  browserAutomationCloseMessageLenientSchema,
  browserAutomationCloseMessageSchema,
  browserAutomationOpenFailedMessageSchema,
  browserAutomationOpenFailureCodeSchema,
  browserAutomationOpenMessageLenientSchema,
  browserAutomationOpenMessageSchema,
  browserAutomationOpenReadyMessageSchema,
  browserAutomationPageStateSchema,
  browserAutomationSnapshotRefSchema,
  parseBrowserSnapshotRef,
  browserAutomationTargetClosedMessageSchema,
  browserAutomationTargetSchema,
  browserAutomationTargetStatusSchema,
  browserAutomationUrlSchema,
  changedMessageLenientSchema,
  changedMessageSchema,
  ENVIRONMENT_CHANGE_KINDS,
  environmentChangedMessageSchema,
  environmentChangeKindSchema,
  HOST_CHANGE_KINDS,
  hostChangedMessageSchema,
  hostChangeKindSchema,
  pingMessageSchema,
  pongMessageLenientSchema,
  pongMessageSchema,
  PROJECT_CHANGE_KINDS,
  projectChangedMessageSchema,
  projectChangeKindSchema,
  realtimeSubscriptionTargetKey,
  realtimeSubscriptionTargetSchema,
  systemChangedMessageSchema,
  systemChangeKindSchema,
  SYSTEM_CHANGE_KINDS,
  threadChangedMessageSchema,
  threadChangeKindSchema,
  threadChangeMetadataSchema,
  THREAD_CHANGE_KINDS,
} from "@bb/domain";

export type {
  BrowserAutomationCapabilityMessage,
  BrowserAutomationCapabilityUnavailableMessage,
  BrowserAutomationCancelMessage,
  BrowserAutomationCancelRequestMessage,
  BrowserAutomationClientMessage,
  BrowserAutomationCommand,
  BrowserAutomationCommandErrorCode,
  BrowserAutomationCommandFailedMessage,
  BrowserAutomationCommandMessage,
  BrowserAutomationCommandResult,
  BrowserAutomationCommandResultMessage,
  BrowserAutomationClientUnavailableReason,
  BrowserAutomationCloseMessage,
  BrowserAutomationOpenFailedMessage,
  BrowserAutomationOpenFailureCode,
  BrowserAutomationOpenMessage,
  BrowserAutomationOpenReadyMessage,
  BrowserAutomationPageState,
  BrowserAutomationSnapshotNode,
  BrowserAutomationSnapshotRef,
  BrowserAutomationTarget,
  BrowserAutomationTargetClosedMessage,
  BrowserAutomationTargetStatus,
  ChangedMessage,
  ClientMessage,
  EnvironmentChangeKind,
  EnvironmentChangedMessage,
  HostChangeKind,
  HostChangedMessage,
  PingMessage,
  PongMessage,
  ProjectChangeKind,
  ProjectChangedMessage,
  RealtimeSubscriptionTarget,
  SubscribeMessage,
  SystemChangeKind,
  SystemChangedMessage,
  ThreadChangeMetadata,
  ThreadChangeKind,
  ThreadChangedMessage,
  UnsubscribeMessage,
  JsonValue,
} from "@bb/domain";
